services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    environment:
      - CASSANDRA_USER=elmo
      - CASSANDRA_PASSWORD=shakira
    ports:
      - "9042:9042"
    volumes:
      - ./data:/var/lib/cassandra
    command: 
      ["cassandra", "-f"]
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES;"]
      interval: 10s
      timeout: 10s
      retries: 5

  grafana:
    depends_on:
      cassandra:
        condition: service_healthy
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'  