version: '3'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra_db
    environment:
      - CASSANDRA_USER=elmo
      - CASSANDRA_PASSWORD=shakira
    ports:
      - "9042:9042"
    volumes:
      - ./data:/var/lib/cassandra
    command: ["cassandra", "-f"]
    
  iot-api:
    depends_on:
      - cassandra
    image: iot-api
    container_name: iot-api
    build:
      context: IoTCassandraAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__Cassandra__IP=cassandra
    ports:
      - 7045:80
      - 17045:443    