services:    
  topicos-api:
    image: topicos-api
    container_name: topicos-api
    build:
      context: IoTCassandraAPI
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Settings__Cassandra__IP=cassandra
    ports:
      - 7045:80
      - 17045:443   
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7045/Health/isalive"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 60s

  topicos-etl:
    depends_on:
      topicos-api:
        condition: service_healthy
    image: topicos-etl
    container_name: topicos-etl
    build:
      context: ETL