{
 "title": "Topicos",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "greenhouse_name",
    "label": "Estufa",
    "query": {
     "query": "SELECT greenhouse\nFROM topicos.greenhouse_list;"
    }
   },
   {
    "name": "greenhouse_id",
    "query": {
     "query": "SELECT id\nFROM topicos.greenhouse_list\nWHERE greenhouse = 'Matheus';"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dados Básicos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Humidade do Ar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "air humidity",
     "target": "SELECT greenhouse  AS name, register_date AS date, value AS data\nFROM topicos.air_humidity\nWHERE greenhouse = '${greenhouse_id}'\nGROUP BY register_date"
    }
   ]
  },
  {
   "title": "Humidade do Ar Atual",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT greenhouse  AS name, register_date AS date, value AS data\nFROM topicos.air_humidity\nWHERE greenhouse = '${greenhouse_id}'"
    }
   ]
  },
  {
   "title": "Humidade do Solo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "soil humidity",
     "target": "SELECT greenhouse  AS name, register_date AS date, value AS data\nFROM topicos.soil_humidity\nWHERE greenhouse = '${greenhouse_id}'\nGROUP BY register_date"
    }
   ]
  },
  {
   "title": "Humidade do Solo Atual",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT greenhouse  AS name, register_date AS date, value AS data\nFROM topicos.soil_humidity\nWHERE greenhouse = '${greenhouse_id}'"
    }
   ]
  },
  {
   "title": "Luminosidade",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "lightness",
     "target": "SELECT greenhouse AS name, register_date AS date, value AS data\nFROM topicos.lightness\nWHERE greenhouse = '${greenhouse_id}'\nGROUP BY register_date"
    }
   ]
  },
  {
   "title": "Temperatura Atual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT greenhouse  AS name, register_date AS date, value AS data\nFROM topicos.temperature\nWHERE greenhouse = '${greenhouse_id}'"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "alias": "temperature",
     "target": "SELECT greenhouse  AS name, register_date AS date, value AS data\nFROM topicos.temperature\nWHERE greenhouse = '${greenhouse_id}'\nGROUP BY register_date"
    }
   ]
  },
  {
   "title": "Uso da Bomba",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "alias": "pump",
     "target": "SELECT greenhouse AS name, register_date AS date, value AS data\nFROM topicos.pump\nWHERE greenhouse = '${greenhouse_id}'\nGROUP BY register_date"
    }
   ]
  },
  { "title": "Comparativos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Humidade do Ar x Humidade do Solo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "SELECT greenhouse AS name, register_date AS date, \nair_humidity_value AS air, soil_humidity_value AS soil\nFROM topicos.soil_humidity_air_humidity\nWHERE greenhouse = '72b302bf297a228a75730123efef7c41'\nGROUP BY register_date"
    }
   ]
  },
  {
   "title": "Humidade do Ar x Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "target": "SELECT greenhouse AS name, register_date AS date, air_humidity_value AS air, temperature_value AS temperature\nFROM topicos.temperature_air_humidity\nWHERE greenhouse = '72b302bf297a228a75730123efef7c41'\nGROUP BY register_date"
    }
   ]
  },
  {
   "title": "Temperatura x Uso da Bomba",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "target": "SELECT greenhouse AS name, register_date AS date, pump_value AS pump, temperature_value AS temperature\nFROM topicos.temperature_pump\nWHERE greenhouse = '72b302bf297a228a75730123efef7c41'\nGROUP BY register_date"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } }
 ]
}