FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Topicos/ETL/", "ETL/"]
COPY ["Topicos/Domain/", "Domain/"]
RUN dotnet restore "ETL/ETL.sln"
COPY . .
WORKDIR "/src/ETL"
RUN dotnet build "ETL.sln" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ETL.sln" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ETL.dll"]